development:
  morphology: stem_enru
  charset_type: utf-8
  charset_table: "0..9, a..z, _, @, A..Z->a..z, U+410..U+42F->U+430..U+44F, U+430..U+44F"
test:
  morphology: stem_enru
  charset_type: utf-8
  charset_table: "0..9, a..z, _, @, A..Z->a..z, U+410..U+42F->U+430..U+44F, U+430..U+44F"
production:
  morphology: stem_enru
  charset_type: utf-8
  charset_table: "0..9, a..z, _, @, A..Z->a..z, U+410..U+42F->U+430..U+44F, U+430..U+44F" 